name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Deploy no EC2 da AWS
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "Configurando chave SSH"
        echo "$SSH_KEY" > private_key && chmod 600 private_key
        eval "$(ssh-agent -s)"
        ssh-add private_key
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-44-221-238-137.compute-1.amazonaws.com << 'EOF'
          cd POC/
          git pull
          ./start.sh
        EOF
    - name: Render Deploy Actions
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-csfnve9u0jms73fj0q7g
        api-key: ${{ secrets.RENDER_API_KEY }}
